[tool.poetry]
name = "bella"
version = "0.1.0"
description = ""
authors = ["Bespoke Labs <company@bespokelabs.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
litellm = "*"
openai = "*"
instructor = "*"
cloudpickle = ">=3.1.0"
dask = ">=2024.10.0"
pydantic = ">=2.9.2"
datasets = "^3.0.2"
ipython = "^8.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
