name: Python Linting

on: [push, pull_request]

jobs:
  PythonLinting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run ruff
      run: |
        poetry run ruff check . --output-format=github
        poetry run ruff format . --check
