name: Curator testing workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run integrations tests
        run: |
          make test_integration openai # Hardcoding it.
          
      - name: Upload coverage report
        if: success()
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
